"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import type {HistoryJob,Scope} from "@/lib/history";
import {elapsed,percent,runNumber} from "@/lib/format";
import {useNotice} from './use-notice';
type Result={jobs:HistoryJob[];total:number;limit:number;statuses:string[]};
export default function HistoryList({scope="workflows",refreshVersion=0}:{scope?:Scope;refreshVersion?:number}){
  const [search,setSearch]=useState(""),[status,setStatus]=useState("ALL"),[sort,setSort]=useState("newest"),[page,setPage]=useState(1),[version,setVersion]=useState(0),[data,setData]=useState<Result|null>(null);const [error,setError]=useNotice();
  const route=scope==="tools"?"tools":"history";
  useEffect(()=>{const c=new AbortController();async function load(){try{const p=new URLSearchParams({search,status,sort,page:String(page)});const r=await fetch(`/api/${route}?${p}`,{cache:"no-store",signal:c.signal});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setError("");}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:"Không tải được history.");}}const initial=setTimeout(()=>void load(),200),timer=setInterval(()=>void load(),5000);return()=>{clearTimeout(initial);clearInterval(timer);c.abort();};},[search,status,sort,page,version,refreshVersion,route,setError]);
  async function remove(job:HistoryJob){const label=scope==="tools"?"Tool Run":"Workflow";if(!window.confirm(`Xóa ${label} #${runNumber(job.workflow_no)} và toàn bộ file liên quan?\nThao tác này không thể hoàn tác.`))return;try{const r=await fetch(`/api/${route}/${job.id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirm:job.workflow_no})});const d=await r.json();if(!r.ok)throw new Error(d.error);setVersion(v=>v+1);}catch(e){setError(e instanceof Error?e.message:"Không xóa được run.");}}
  return <section className="jobs-section history-list"><div className="history-filters"><label>Search<input type="search" value={search} placeholder="Số, tên hoặc nguồn…" onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="ALL">All statuses</option>{data?.statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label><button className="refresh" onClick={()=>setVersion(v=>v+1)}>↻ Làm mới</button></div>{error&&<p className="alert" role="alert">{error}</p>}
    <div className="table-wrap"><table><thead><tr><th>{scope==="tools"?"Tool #":"Workflow #"}</th><th>Source / Input</th><th>Created</th><th>Status</th><th>Progress</th><th>Total Time</th><th>Outputs</th><th>Actions</th></tr></thead><tbody>{data?.jobs.map(job=><tr key={job.id}><td className="name-cell"><Link href={`/${route}/${job.id}`}><strong>#{runNumber(job.workflow_no)}</strong></Link><small>{job.tool_type||job.name}</small></td><td><span className="history-source" title={job.url}>{job.input_file||job.url||"—"}</span></td><td>{new Date(job.created_at).toLocaleString("vi-VN")}</td><td>{job.status}</td><td>{percent(job.progress)}</td><td>{elapsed(job.total_duration_ms)}</td><td>{job.files.filter(f=>f.status==="AVAILABLE").length} files{job.files.some(f=>f.status==="STALE")&&<small> · STALE outputs</small>}</td><td className="history-actions"><Link href={`/${route}/${job.id}`}>View / Download</Link>{scope==="workflows"&&<Link href={`/reprocess?id=${job.id}`}>Reprocess</Link>}<button className="text-button" disabled={!["COMPLETED","FAILED","CANCELLED","PARTIAL","DELETING"].includes(job.status)} onClick={()=>void remove(job)}>Delete</button></td></tr>)}</tbody></table></div>{data?.total===0&&<p className="empty">Chưa có kết quả phù hợp.</p>}{data&&<div className="history-pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>← Previous</button><span>{data.total} runs · Page {page}</span><button disabled={page*data.limit>=data.total} onClick={()=>setPage(p=>p+1)}>Next →</button></div>}
  </section>;
}
