"use client";
import { useState } from "react";
import SiteHeader from "@/components/layout/site-header";
import VoiceSelect from "@/components/voice/voice-select";
import HistoryList from "@/components/history/history-list";
import { useLicense } from "@/components/license/license-status";
import { useNotice } from '@/components/common/use-notice';
import FilePicker from '@/components/common/file-picker';
import AddressProfileSelect from "@/components/voice/address-profile-select";
import TranslationModeSelect from "@/components/voice/translation-mode-select";
import AutoTtsToggle from "@/components/voice/auto-tts-toggle";
import type { TranslationMode } from "@/lib/shared/translation-modes";
import { useLanguage } from '@/lib/i18n/language-context';
const tools = [{ id: "transcription", label: "Chinese Audio → Chinese Text" }, { id: "translation", label: "Chinese Text → Vietnamese Text" }, { id: "moderation", label: "Vietnamese Text → Moderated Vietnamese" }, { id: "tts", label: "Vietnamese Text → Vietnamese Voice" }];
export default function Tools() {
  const { t , tr} = useLanguage();
  const license = useLicense(); const [tool, setTool] = useState("translation"), [voice, setVoice] = useState(""), [style, setStyle] = useState(""), [address, setAddress] = useState(""), [mode, setMode] = useState<TranslationMode>("normal"), [auto, setAuto] = useState(false),[source, setSource] = useState<"file" | "link">("file"), [link, setLink] = useState(""), [file, setFile] = useState<File | null>(null), [busy, setBusy] = useState(false), [version, setVersion] = useState(0); const [message, setMessage] = useNotice();
  // Tool 1 produces Chinese text, which the Basic edition never exposes.
  const available = tools.filter(item => item.id !== "transcription" || license.plus);
  const byLink = tool === "transcription" && source === "link";
  async function run(e: React.FormEvent) { e.preventDefault(); if (byLink ? !link.trim() : !file) return; setBusy(true); setMessage(""); try { let r: Response; if (byLink) { r = await fetch("/api/tools", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tool, url: link.trim() }) }); } else { const f = file as File; const p = new URLSearchParams({ tool, name: f.name, voice, ...(tool === "tts" && style ? { style } : {}), ...(tool === "tts" && license.edition === "basic" && auto ? { auto: "1" } : {}),...(tool === "translation" && mode === "genius" ? { mode } : {}), ...(tool === "translation" && mode === "normal" && address ? { address } : {}) }); r = await fetch(`/api/tools?${p}`, { method: "POST", headers: { "Content-Type": f.type || "application/octet-stream" }, body: f }); } const d = await r.json(); if (!r.ok) throw new Error(d.error); setMessage(tr("Tool run đã được thêm vào hàng đợi.")); setLink(""); setVersion(v => v + 1); } catch (e) { setMessage(e instanceof Error ? tr(e.message) : tr("Upload thất bại.")); } finally { setBusy(false); } }
  return <main className="studio"><SiteHeader /><section className="hero"><span className="eyebrow">{t.tools.eyebrow}</span><h1>{t.tools.title}</h1><p>{t.tools.subtitle}</p><div className="tool-cards">{available.map(item => <button type="button" className={`tool-card ${tool === item.id ? "selected" : ""}`} aria-pressed={tool === item.id} key={item.id} onClick={() => { setTool(item.id); setFile(null); }}>{tr(item.label)}</button>)}</div><form onSubmit={run} className="tool-form">{tool === "transcription" && <div className="voice-style-options" role="radiogroup" aria-label={tr("Nguồn âm thanh")}>{(["file", "link"] as const).map(value => <button key={value} type="button" role="radio" aria-checked={source === value} className={`voice-style-option${source === value ? " selected" : ""}`} onClick={() => setSource(value)}>{value === "file" ? tr("Tệp âm thanh") : tr("Link YouTube")}</button>)}</div>}{byLink ? <input type="url" value={link} onChange={event => setLink(event.target.value)} placeholder="https://www.youtube.com/watch?v=..." aria-label={tr("Link YouTube")} required /> : <FilePicker key={tool} accept={tool === "transcription" ? ".wav,.mp3,.m4a,.flac,.ogg,.aac,.webm,.mp4" : ".txt,.md,.jsonl"} file={file} onChange={setFile} />}{tool === "translation" && <TranslationModeSelect value={mode} onChange={setMode} />}{tool === "translation" && mode === "normal" && <AddressProfileSelect value={address} onChange={setAddress} />}{tool === "tts" && <VoiceSelect value={voice} onChange={setVoice} style={style} onStyleChange={setStyle} />}{tool === "tts" && license.edition === "basic" && <AutoTtsToggle checked={auto} onChange={setAuto} />}<button disabled={busy || !license.allowed || (byLink ? !link.trim() : !file)}>{busy ? t.tools.uploading : t.tools.run}</button></form>{message && <p className="alert" role="status">{message}</p>}</section><h2>{t.tools.historyHeading}</h2><HistoryList scope="tools" refreshVersion={version} /></main>;
}
