"use client";
import { useLanguage } from "@/lib/i18n/language-context";
import { openBillingPage } from "@/lib/shared/billing-client";
import {useEffect,useState} from "react";
import type {Job,Step} from "@/lib/server/jobs";
import {elapsed,percent,runNumber} from "@/lib/shared/format";
import {transcriptionView, type TranscriptionStep} from "@/lib/server/transcription-progress";
type Run=Pick<Job,"id"|"workflow_no"|"steps"|"stages"|"progress"|"started_at"|"run_started_at"|"completed_at"|"total_duration_ms"|"tool_steps"|"transcription_steps"|"chunks_done"|"chunks_total"|"duration_ms"|"processed_ms"|"asr_runtime"|"translation_runtime"|"translation_progress"|"pause_requested"|"delete_requested"|"storage_scope"|"memory_pause_reason"|"lane"> & {status:string;pause_reason?:string|null;genius_progress?:Job["genius_progress"];translation_mode?:Job["translation_mode"];tts_remote_progress?:Job["tts_remote_progress"]};
export default function PipelineStatus({job}:{job:Run;readOnly?:boolean}){
  const { tr } = useLanguage();
  const [clock,setClock]=useState(0);
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[]);
  const effective=job.tool_steps||["DOWNLOAD","TRANSCRIPTION","TRANSLATION","MODERATION","TTS"] as Step[];
  const active=!["COMPLETED","FAILED","CANCELLED","PAUSED","PARTIAL","DELETING"].includes(job.status);
  const time=(start?:string|null)=>start&&clock?Math.max(0,clock-Date.parse(start)):0;
  const phases=transcriptionView(job);
  const rows=effective.flatMap<{label:string;item:TranscriptionStep|undefined}>(stage=>stage==='TRANSCRIPTION'?phases.map((item,index)=>({label:`${tr("TRANSCRIPTION")} ${index+1}/4`,item:{...item,output_manifest:index===3?job.steps?.TRANSCRIPTION?.output_manifest:undefined}})): [{label:tr(stage),item:job.steps?.[stage]}]);
  const translation=job.steps?.TRANSLATION?.state==='RUNNING'?job.translation_runtime:undefined;
  const preparing=translation&&['MODEL_LOADING','WAITING_MEMORY','WAITING_TEMPERATURE'].includes(translation.state);
  const status=job.delete_requested?tr("ĐANG HỦY VÀ XÓA"):job.pause_requested?tr("ĐANG DỪNG SAU TASK HIỆN TẠI"):['VAD','TRANSCRIBING','MERGING','TRANSCRIPTION_COMPLETED'].includes(job.status)?tr("TRANSCRIPTION"):tr(job.status);
  return <section className="pipeline-status"><h3>#{runNumber(job.workflow_no)} · {status}</h3><p>{tr("Overall:")} {percent(job.progress)} {tr("· Total:")} {elapsed(active&&job.run_started_at?(job.total_duration_ms||0)+time(job.run_started_at):job.total_duration_ms)}</p><small>{tr("overallNote", {count: effective.length})}</small><div className="progress-track">{job.progress!=null&&<div style={{width:`${job.progress}%`}}/>}</div>
    <table><thead><tr><th>{tr("Stage")}</th><th>{tr("Status")}</th><th>{tr("Progress")}</th><th>{tr("Elapsed")}</th><th title={tr("Số lần bắt đầu chạy; 0: chưa chạy, 1: lần đầu, 2: lần thứ hai")}>{tr("Attempt")}</th><th title={tr("Chỉ đếm file kết quả đã xuất, không đếm cache nội bộ")}>{tr("Output")}</th></tr></thead><tbody>{rows.map(({label,item})=>{const isTranslation=label===tr('TRANSLATION');const value=item?.state==='COMPLETED'?100:isTranslation&&preparing?null:item?.progress;const waiting=item?.state==='RUNNING'&&!!(item.wait_started_at||(label===`${tr('TRANSCRIPTION')} 3/4`&&job.asr_runtime?.state==='WAITING_MEMORY')||(isTranslation&&translation?.state==='WAITING_MEMORY'));return <tr key={label}><td>{label}</td><td>{tr(waiting?'Chờ RAM':item?.state||'PENDING')}</td><td>{percent(value)}{item?.state==='RUNNING'&&value==null&&<span role="status" aria-label={tr("Đang xử lý")} className="indeterminate"> ⟳</span>}</td><td>{elapsed(item?.state==='RUNNING'?item.started_at?Math.max(0,(item.duration_ms||0)+time(item.started_at)-(item.memory_wait_run_ms||0)-(waiting?(isTranslation?(translation?.wait_seconds||0)*1000:time(item.wait_started_at||job.asr_runtime?.wait_started_at||item.started_at)):0)):null:item?.duration_ms)}</td><td>{item?.inferred?'—':item?.attempt||0}</td><td>{item?.output_manifest?.filter(f=>f.status==='AVAILABLE').length||0} {tr("files")}{item?.output_manifest?.some(f=>f.status==='STALE')&&` · ${tr('STALE')}`}</td></tr>;})}</tbody></table>
    <small>{tr("Attempt = số lần bắt đầu chạy bước. Output chỉ tính kết quả đã xuất; audio tải về và checkpoint được lưu nội bộ.")}</small>
    {job.steps?.TRANSCRIPTION?.state==='RUNNING'&&job.asr_runtime?.state==='WAITING_MEMORY'&&<p role="status">{tr('memoryWaitNote',{seconds:Math.floor(time(job.asr_runtime.wait_started_at)/1000),limit:job.asr_runtime.wait_timeout_seconds??120})}</p>}
    {job.steps?.TRANSCRIPTION?.state==='RUNNING'&&job.asr_runtime?.state==='DOWNLOADING_MODELS'&&<p role="status">{job.asr_runtime.total_gib?tr('modelsDownloadingTotal',{gib:(job.asr_runtime.downloaded_gib??0).toFixed(2),of:job.asr_runtime.total_gib.toFixed(2),index:job.asr_runtime.file_index??1,files:job.asr_runtime.file_total??1}):tr('modelsDownloading',{index:job.asr_runtime.model_index??1,total:job.asr_runtime.model_total??1,gib:(job.asr_runtime.downloaded_gib??0).toFixed(2)})}</p>}
    {job.steps?.TRANSCRIPTION?.state==='RUNNING'&&job.asr_runtime?.tuning_deferred&&<p role="status">{tr('Hoãn hiệu chỉnh CPU khi RAM ít')}</p>}
    {job.status==='PAUSED'&&job.memory_pause_reason&&<p role="status">{tr(job.memory_pause_reason)}</p>}
    {job.status==='PAUSED'&&job.pause_reason&&<p role="alert">{tr(`pause.${job.pause_reason}`)}</p>}
    {job.status==='PAUSED'&&job.pause_reason==='CREDIT_LIMIT'&&<p><button type="button" className="action-button" onClick={()=>void openBillingPage("debt").then(r=>{if(!r.ok)alert(tr(r.error==='BILLING_CODE_UNKNOWN'?r.error:'billingUnavailable'));})}>{tr('billingPayDebt')}</button></p>}
    {job.genius_progress&&<p role="status"><small>{tr('geniusProgress',{done:job.genius_progress.chunks_done,total:job.genius_progress.chunks_total,rows:job.genius_progress.rows_done,allRows:job.genius_progress.rows_total,chars:job.genius_progress.billed_chars.toLocaleString()})}</small></p>}
    {job.tts_remote_progress&&<p role="status"><small>{tr('ttsRemoteProgress',{units:job.tts_remote_progress.units_done,chars:job.tts_remote_progress.billed_chars.toLocaleString()})}</small></p>}
    {!!job.genius_progress?.flagged_rows.length&&<p role="status">{tr('geniusFlagged',{count:job.genius_progress.flagged_rows.length,rows:job.genius_progress.flagged_rows.slice(0,30).join(', ')+(job.genius_progress.flagged_rows.length>30?'…':'')})}</p>}
    {job.lane&&job.lane.workflows>1&&job.lane.target!=null&&<p role="status">{tr('laneStatus',{workflows:job.lane.workflows,units:job.lane.units,target:job.lane.target,cores:job.lane.cores})}{job.lane.yielding_for!=null&&<> · {tr('laneYielding',{workflow:runNumber(job.lane.yielding_for)})}</>}{job.lane.waiting&&<> · {tr('laneWaiting')}</>}</p>}
    {job.steps?.TRANSCRIPTION?.state==='RUNNING'&&job.asr_runtime&&<p role="status">{tr("Auto CPU:")} {job.asr_runtime.state==='WAITING_MEMORY'?tr("ramWaiting", {available: job.asr_runtime.ram_available_gib ?? "—", required: job.asr_runtime.required_available_gib ?? "—"}):job.asr_runtime.state==='CALIBRATING'?tr("Đang đo cấu hình CPU phù hợp…"):`${tr("cpuWorkers", {workers: job.asr_runtime.workers ?? "—", threads: job.asr_runtime.threads ?? "—"})}${job.asr_runtime.throttled?tr(" · Đang giảm tải"):''}`}</p>}
    {translation&&<p role="status">{tr('TRANSLATION')} · {translation.device==='gpu'?tr('Auto GPU:'):tr('Auto CPU:')} {translation.state==='MODEL_LOADING'?tr('Đang nạp mô hình'):translation.state==='WAITING_TEMPERATURE'?tr('Chờ máy giảm nhiệt'):translation.state==='WAITING_MEMORY'?translation.required_vram_gib?tr('translationVramWaiting',{required:translation.required_vram_gib.toFixed(2)}):tr('ramWaiting',{available:translation.available_gib??'—',required:translation.required_available_gib??'—'}):tr('translationSlots',{slots:translation.slots??1,threads:translation.threads??'—'})}{translation.throttled&&tr(' · Đang giảm tải')}</p>}
    {translation?.mode==='resource'&&<p><small>{tr('translationResourcePolicy',{start:translation.start_free_gib??3.5,extra:translation.extra_slot_gib??0.4,reserve:translation.reserve_gib??2,cpu:translation.cpu_target??85,gpu:translation.gpu_target??85,temperature:translation.temperature_limit??85})}</small></p>}
    {translation?.state==='WAITING_MEMORY'&&translation.wait_timeout_seconds!=null&&<p role="status">{tr('translationMemoryWaitNote',{seconds:translation.wait_seconds??0,limit:translation.wait_timeout_seconds})}</p>}
    {job.translation_progress&&<p><small>{tr('translationPrefixProgress',{done:job.translation_progress.done,total:job.translation_progress.total,exported:job.translation_progress.exported_rows})}</small></p>}
    {phases.some(item=>item.inferred)&&effective.includes('TRANSCRIPTION')&&<p><small>{tr("Phiên cũ: tiến độ được suy ra từ checkpoint; thời gian không có dữ liệu và Attempt từng bước hiển thị —.")}</small></p>}
  </section>;
}
