"""Generate every logo/icon file from one source image (needs Pillow: `pip install pillow`; not a runtime dependency).

    python packaging/make_icons.py                          uses branding/logo-source.png
    python packaging/make_icons.py --source new-logo.png    replaces the source first

Writes (all under the workspace):
  audio-translates/public/arsneonci-logo.png     app header avatar (512x512)
  audio-translates/app/favicon.ico               browser tab icon of the app
  audio-translates/packaging/app-icon.ico        installer .exe icon and Start-menu shortcut icon
  admin-system/ui/favicon.ico                    browser tab icon of the admin site
  billing-gateway/brand.py                       tab icon of the Billing portal, as a data: address (the portal serves no files)
The logo is cropped to its visible part and centred on a transparent square, so it does not shrink to a dot at 16 px.
"""
import argparse
import base64
import io
from pathlib import Path
import shutil

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
APP = ROOT / 'audio-translates'
SOURCE = APP / 'branding' / 'logo-source.png'


def square(source, padding=0.03):
    image = Image.open(source).convert('RGBA')
    box = image.getchannel('A').point(lambda value: 255 if value > 8 else 0).getbbox()
    if not box: raise SystemExit('The logo is fully transparent.')
    image = image.crop(box)
    side = int(max(image.size) * (1 + 2 * padding))
    canvas = Image.new('RGBA', (side, side), (0, 0, 0, 0))
    canvas.paste(image, ((side - image.width) // 2, (side - image.height) // 2), image)
    return canvas


def png(image, size):
    out = io.BytesIO(); image.resize((size, size), Image.LANCZOS).save(out, 'PNG', optimize=True); return out.getvalue()


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--source', type=Path)
    args = parser.parse_args()
    if args.source:
        SOURCE.parent.mkdir(parents=True, exist_ok=True); shutil.copyfile(args.source, SOURCE)
    if not SOURCE.is_file(): raise SystemExit(f'Source logo not found: {SOURCE}')
    master = square(SOURCE)
    (APP / 'public' / 'arsneonci-logo.png').write_bytes(png(master, 512))
    def ico(path, sizes):
        path.parent.mkdir(parents=True, exist_ok=True)
        master.resize((256, 256), Image.LANCZOS).save(path, 'ICO', sizes=[(s, s) for s in sizes])
    ico(APP / 'app' / 'favicon.ico', (16, 32, 48, 64, 128, 256))
    ico(APP / 'packaging' / 'app-icon.ico', (16, 24, 32, 48, 64, 128, 256))
    ico(ROOT / 'admin-system' / 'ui' / 'favicon.ico', (16, 32, 48, 64))
    data = base64.b64encode(png(master, 64)).decode()
    (ROOT / 'billing-gateway' / 'brand.py').write_text(
        '"""Generated by audio-translates/packaging/make_icons.py - do not edit by hand."""\n'
        f'ICON = "data:image/png;base64,{data}"\n', encoding='utf-8', newline='\n')
    print('Icons written from', SOURCE)


if __name__ == '__main__':
    main()
